# Generated by Django 4.2.4 on 2023-11-08 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_global_psychotrauma_screen_considering_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='hamd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.CharField(blank=True, max_length=250, null=True)),
                ('depressed_mood', models.CharField(blank=True, max_length=250, null=True)),
                ('feeling_of_guilt', models.CharField(blank=True, max_length=250, null=True)),
                ('suicide', models.CharField(blank=True, max_length=250, null=True)),
                ('insomnia_initial', models.CharField(blank=True, max_length=250, null=True)),
                ('insomnia_middle', models.CharField(blank=True, max_length=250, null=True)),
                ('insomnia_delayed', models.CharField(blank=True, max_length=250, null=True)),
                ('work_and_interests', models.CharField(blank=True, max_length=250, null=True)),
                ('retardation_delayed', models.CharField(blank=True, max_length=250, null=True)),
                ('agitation_delayed', models.CharField(blank=True, max_length=250, null=True)),
                ('anxiety_psychic', models.CharField(blank=True, max_length=250, null=True)),
                ('anxiety_somatic', models.CharField(blank=True, max_length=250, null=True)),
                ('somatic_symptoms_gastrointestinal', models.CharField(blank=True, max_length=250, null=True)),
                ('somatic_symptoms_general', models.CharField(blank=True, max_length=250, null=True)),
                ('genital_symptoms', models.CharField(blank=True, max_length=250, null=True)),
                ('hypochondriasis', models.CharField(blank=True, max_length=250, null=True)),
                ('weight_loss', models.CharField(blank=True, max_length=250, null=True)),
                ('insight', models.CharField(blank=True, max_length=250, null=True)),
                ('diurnal_variation', models.CharField(blank=True, max_length=250, null=True)),
                ('depersonalization_and_derelization', models.CharField(blank=True, max_length=250, null=True)),
                ('paranoid_symptoms', models.CharField(blank=True, max_length=250, null=True)),
                ('obsessional_symptoms', models.CharField(blank=True, max_length=250, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.details')),
            ],
        ),
    ]
