# Generated by Django 4.2.4 on 2023-11-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_hamd'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamd',
            name='diurnal_variation_mild_am',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='hamd',
            name='diurnal_variation_mild_pm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='hamd',
            name='diurnal_variation_severe_am',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='hamd',
            name='diurnal_variation_severe_pm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='hamd',
            name='total_score',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
