# Generated by Django 4.2.7 on 2023-11-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_hamd_diurnal_variation_mild_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatives',
            name='is_emergency',
            field=models.BooleanField(default=0),
        ),
    ]
