# Generated by Django 4.2.7 on 2023-11-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_remove_address_apt_remove_address_barangay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responde_date', models.DateTimeField(auto_now_add=True)),
                ('social_phobia', models.CharField(blank=True, max_length=250, null=True)),
                ('generalized_anxiety_disorder', models.CharField(blank=True, max_length=250, null=True)),
                ('major_depressive_disorder', models.CharField(blank=True, max_length=250, null=True)),
                ('Disorder_personality_disorder', models.CharField(blank=True, max_length=250, null=True)),
                ('dysthymia', models.CharField(blank=True, max_length=250, null=True)),
                ('agoraphobia', models.CharField(blank=True, max_length=250, null=True)),
                ('bipolar_disorder', models.CharField(blank=True, max_length=250, null=True)),
                ('drug_dependence', models.CharField(blank=True, max_length=250, null=True)),
                ('mas_babae', models.CharField(blank=True, max_length=250, null=True)),
                ('mas_lalake', models.CharField(blank=True, max_length=250, null=True)),
                ('kalidad_pagtulog', models.CharField(blank=True, max_length=250, null=True)),
                ('iwasan_aktibidad', models.CharField(blank=True, max_length=250, null=True)),
                ('cognitive_behavior_therapy', models.CharField(blank=True, max_length=250, null=True)),
                ('kumpidensyal', models.CharField(blank=True, max_length=250, null=True)),
                ('panganib_na_makapinsala', models.CharField(blank=True, max_length=250, null=True)),
                ('hindi_nagbabanta', models.CharField(blank=True, max_length=250, null=True)),
                ('hahanapin_impormasyon_sakit_isip', models.CharField(blank=True, max_length=250, null=True)),
                ('humingi_impormasyon_sakit_isip', models.CharField(blank=True, max_length=250, null=True)),
                ('pagpapatingin_sa_doktor', models.CharField(blank=True, max_length=250, null=True)),
                ('mapagkukunan_impormasyon_sakit_isip', models.CharField(blank=True, max_length=250, null=True)),
                ('bumalik_tamang_kaisipan', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_kahinaan', models.CharField(blank=True, max_length=250, null=True)),
                ('sakit_medikal', models.CharField(blank=True, max_length=250, null=True)),
                ('mapanganib', models.CharField(blank=True, max_length=250, null=True)),
                ('umiwas_taong_sakit_isip', models.CharField(blank=True, max_length=250, null=True)),
                ('hindi_sasabihin_kahit_kanino', models.CharField(blank=True, max_length=250, null=True)),
                ('question_26', models.CharField(blank=True, max_length=250, null=True)),
                ('question_27', models.CharField(blank=True, max_length=250, null=True)),
                ('hindi_magiging_epektibo', models.CharField(blank=True, max_length=250, null=True)),
                ('lumipat_ng_bahay', models.CharField(blank=True, max_length=250, null=True)),
                ('pakikisalamuha_isang_taong', models.CharField(blank=True, max_length=250, null=True)),
                ('question_31', models.CharField(blank=True, max_length=250, null=True)),
                ('question_32', models.CharField(blank=True, max_length=250, null=True)),
                ('question_33', models.CharField(blank=True, max_length=250, null=True)),
                ('question_34', models.CharField(blank=True, max_length=250, null=True)),
                ('question_35', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.details')),
            ],
        ),
    ]
