# Generated by Django 4.2.7 on 2023-11-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_patient_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_survey',
            old_name='Disorder_personality_disorder',
            new_name='disorder_personality_disorder',
        ),
    ]
