# Generated by Django 4.2.7 on 2023-11-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_rename_disorder_personality_disorder_patient_survey_disorder_personality_disorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_survey',
            name='panganib_na_makapinsala',
        ),
    ]
