# Generated by Django 4.2.7 on 2023-12-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_remove_patient_survey_panganib_na_makapinsala'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='access_to_mental_health',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='employment_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='mental_health_history',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
