# Generated by Django 4.2.7 on 2025-07-13 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0018_alter_considering_event_considering_event_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='considering_event',
            name='score_1_16',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='considering_event',
            name='total_score',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='details_audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_fields', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_edited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
