# Generated by Django 4.2.7 on 2025-07-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_considering_event_score_1_16_and_more'),
        ('patient', '0019_considering_event_score_1_16_and_more'),
    ]

    operations = [
    ]
