# Generated by Django 4.2.7 on 2023-11-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_hamd_diurnal_variation_mild_am_and_more'),
        ('consultation', '0016_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_interaction', models.CharField(blank=True, max_length=250, null=True)),
                ('cconsultation_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.details')),
            ],
        ),
        migrations.CreateModel(
            name='vitalsign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=250, null=True)),
                ('weight', models.CharField(blank=True, max_length=250, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=250, null=True)),
                ('temperature', models.CharField(blank=True, max_length=250, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='chief_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_complaints', models.TextField(blank=True, null=True)),
                ('informant_complaints', models.TextField(blank=True, null=True)),
                ('informatmant_relationship', models.CharField(blank=True, max_length=250, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.encounter')),
            ],
        ),
    ]
