# Generated by Django 4.2.7 on 2025-07-10 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0016_considering_event_score_1_16_and_more'),
        ('consultation', '0019_encounter_consulted_by_encounter_update_by_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='for_follow_up',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='psychiatric_evaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_consultation_date', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psychiatric_evaluate_create_by', to=settings.AUTH_USER_MODEL)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.details')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psychiatric_evaluate_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nurse_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=0)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.encounter')),
            ],
        ),
    ]
